"""
N字战法 + 底部十字星策略配置
"""

import os

# 数据获取与缓存
HISTORY_DAYS = 220
MAX_WORKERS = 8
MAX_RETRY = 2
DB_PATH = os.path.join(os.path.dirname(__file__) or ".", "n_strategy.db")
STOCK_LIST_CACHE_TTL = 24 * 3600
KLINE_INCREMENTAL_FETCH_COUNT = 80
KLINE_FULL_FETCH_COUNT = 500
KLINE_FULL_REFRESH_INTERVAL_DAYS = 7
INDEX_FULL_REFRESH_INTERVAL_DAYS = 3
BACKTEST_NOTIFY_HOLDING_DAY = 5

# 大盘过滤
MARKET_INDEX_CODE = "000001"  # 上证指数
MARKET_MA_PERIOD = 20
MARKET_DAILY_GAIN_PCT = 1.0

# 阶段一：底部十字星
DOJI_LOOKBACK_MIN = 5
DOJI_LOOKBACK_MAX = 15
PREV_DROP_LOOKBACK = 20
PREV_DROP_THRESHOLD = -15.0
DOJI_BODY_TO_RANGE_MAX = 1 / 3
DOJI_SHADOW_SIMILARITY_MAX = 0.4
HAMMER_LOWER_SHADOW_MIN = 0.5

# 阶段二：第一笔拉升
SURGE_GAIN_PCT = 5.0
SURGE_VOLUME_RATIO = 1.5
SURGE_LOOKBACK_DAYS = 10

# 阶段三：缩量回调
PULLBACK_DAYS_MIN = 2
PULLBACK_DAYS_MAX = 5
PULLBACK_VOLUME_SHRINK = 0.5

# 阶段四：突破确认
BREAKOUT_PULLBACK_VOLUME_MULTIPLIER = 2.0

# KDJ
KDJ_LOOKBACK = 9
KDJ_SMOOTH_K = 3
KDJ_SMOOTH_D = 3
J_OVERSOLD_THRESHOLD = 0.0
J_LOW_THRESHOLD = 10.0
K_LOW_THRESHOLD = 20.0

# 个股底部区域
BOTTOM_REGION_LOOKBACK = 60
BOTTOM_REGION_BUFFER = 0.2

# 输出
RESULT_OUTPUT = "n_strategy_signals.csv"
RESULT_TOP_N = 20

# 通知
FEISHU_ENABLED = True
FEISHU_WEBHOOK_URL = os.getenv("FEISHU_WEBHOOK_URL", "")
FEISHU_MESSAGE_MODE = os.getenv("FEISHU_MESSAGE_MODE", "card").lower()
